SklepUKW2024/Models/AddFilmViewModel.cs
namespace SklepUKW2024.Models
{
	public class AddFilmViewModel
	{
        public Film Film { get; set; }

        public List<Category> Categories { get; set; }

        public IFormFile Poster { get; set; }
    }
}

SklepUKW2024/Models/Film.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SklepUKW2024.Models
{
    public class Film
    {
        // klucz główny 
        // inne opcje: Id lub anotacja [Key]
        public int FilmId { get; set; }

        [Required(ErrorMessage = "Wpisz tytuł")]
        public string Title { get; set; }

        public string Director { get; set; }

        [StringLength(500)]
        public string Desc { get; set; }

        public double? Price { get; set; }

        public DateTime? AddDate { get; set; }

        public string? Poster { get; set; }

        // Klucz obcy
        // Inne opcje: CategoryCategoryId
        // [ForeignKey("Category")]
        public int CategoryId { get; set; }

        public Category Category { get; set; }
    }
}

SklepUKW2024/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SklepUKW2024.DAL;
using SklepUKW2024.Infrastructure;
using SklepUKW2024.Models;
using System.Dynamic;

namespace SklepUKW2024.Controllers
{
    public class CartController : Controller
	{
		FilmsContext db;

		public CartController(FilmsContext db)
		{
			this.db = db;
		}
		[Route("/koszyk")]
		public IActionResult Index()
		{
			var cart = CartMenager.GetCartItems(HttpContext.Session);
			double? sum = cart.Sum(item => item.Quantity * item.Film.Price);
			ViewBag.total = sum;

			return View(cart);
		}

		public IActionResult AddToCart(int filmId) 
		{
			CartMenager.AddToCart(HttpContext.Session, filmId, db);
			return RedirectToAction("Index");
		}
		public IActionResult Remove(int filmId)
		{
			var model = new ItemRemoveViewModel()
			{
				itemId = filmId,
				itemQuantity = CartMenager.RemoveFromCart(HttpContext.Session,filmId),
				cartValue = CartMenager.GetCartValue(HttpContext.Session)
			};
			return Json(model);
		}
		private int GetIndex(int filmId)
		{
			var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, Consts.CartSessionKey);

			for (int i = 0; i < cart.Count; i++)
			{
				if (cart[i].Film.FilmId.Equals(filmId))
				{
					return i;
				}
			}

			return -1;
		}
		
	}
}

SklepUKW2024/Controllers/FilmsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using SklepUKW2024.DAL;
using SklepUKW2024.Models;

namespace SklepUKW2024.Controllers
{
	public class FilmsController : Controller
	{
		FilmsContext db;
		IWebHostEnvironment hostingEnvironment;

		public FilmsController(FilmsContext db, IWebHostEnvironment hostingEnvironment)
		{
			this.db = db;
			this.hostingEnvironment = hostingEnvironment;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult FilmsList(string categoryName)
		{
			var category = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).Single();

			var filmsFromCategory = category.Films.ToList();

			return View(filmsFromCategory);
		}

		public IActionResult Details(int filmId)
		{
			var film = db.Films.Find(filmId);
			var category = db.Categories.Find(film.CategoryId);

			return View(film);
		}

		[HttpGet]
		public IActionResult AddFilm()
		{
			var model = new AddFilmViewModel();
			model.Categories = db.Categories.ToList();

			return View(model);
		}

		[HttpPost]
		public IActionResult AddFilm(AddFilmViewModel model)
		{
			model.Film.AddDate = DateTime.Now;

			var picFolderPath = Path.Combine(hostingEnvironment.WebRootPath, "obrazki");
			var uniquePosterName = Guid.NewGuid() + "_" + model.Poster.FileName;
			model.Film.Poster = uniquePosterName;

			var fullPath = Path.Combine(picFolderPath, uniquePosterName);

			model.Poster.CopyTo(new FileStream(fullPath, FileMode.Create));

			db.Films.Add(model.Film);
			db.SaveChanges();

			//var film = db.Films.Find(model.Film.FilmId);

			return RedirectToAction("Details", new { filmId = model.Film.FilmId });
		}



		[HttpGet]
		public IActionResult EditFilm(int filmId)
		{
			var film = db.Films.Where(f => f.FilmId == filmId).FirstOrDefault();
			var category = db.Categories.Find(film.CategoryId);

			return View(film);
		}


		[HttpPost]
		public IActionResult EditFilm(Film model)
		{
			var film = db.Films.Where(f=>f.FilmId == model.FilmId).FirstOrDefault();

			film.Title = model.Title;
			film.Director = model.Director;
			film.Desc = model.Desc;
			film.Price = model.Price;

			db.Entry(film).State = EntityState.Modified;
			db.SaveChanges();

			return RedirectToAction("Details", new { filmId = model.FilmId });
		}

	}
}

SklepUKW2024/ViewComponents/CategoryFilmsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SklepUKW2024.DAL;

namespace SklepUKW2024.ViewComponents
{
	public class CategoryFilmsViewComponent : ViewComponent
	{
		FilmsContext db;

		public CategoryFilmsViewComponent(FilmsContext db)
		{
			this.db = db;
		}

		public async Task<IViewComponentResult> InvokeAsync(string categoryName)
		{
			var model = db.Categories.Include("Films").Where(c => c.Name.ToUpper() == categoryName.ToUpper()).Single().Films.ToList();
			model = model.OrderBy(f => f.Title).ToList();

			return await Task.FromResult((IViewComponentResult)View("_CategoryFilms", model));
		}
	}
}

SklepUKW2024/Views/Films/AddFilm.cshtml
@model AddFilmViewModel


@using (Html.BeginForm("AddFilm", "Films", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
	<div class="form-group">
		@Html.LabelFor(m => m.Film.Title, "Tytuł filmu:")
		@Html.TextBoxFor(m => m.Film.Title, new { @class="form-control", @required=true })
	</div>
	<div class="form-group">
		@Html.LabelFor(m => m.Film.Director, "Reżyser:")
		@Html.TextBoxFor(m => m.Film.Director, new { @class="form-control", @required=true })
	</div>
	<div class="form-group">
		@Html.LabelFor(m => m.Film.Desc, "Opis:")
		@Html.TextBoxFor(m => m.Film.Desc, new { @class="form-control", @required=true })
	</div>
	<div class="form-group">
		@Html.LabelFor(m => m.Film.Price, "Cena:")
		@Html.TextBoxFor(m => m.Film.Price, new { @class="form-control", @required=true })
	</div>

	<div class="form-check">
		@foreach (var category in Model.Categories)
		{
			@Html.RadioButtonFor(m => m.Film.CategoryId, category.CategoryId, new { @class = "form-check-input"}) 
			@category.Name
			<br />
		}
	</div>

	<div class="form-group">
		@Html.LabelFor(m => m.Poster, "Wybierz plakat: ")
		@Html.TextBoxFor(m => m.Poster, new { @type="file", @class="form-control-file", @required=true })
	</div>


	<button type="submit" class="btn btn-primary btn-dodaj"> Dodaj </button>
}

SklepUKW2024/Views/Films/Details.cshtml
@model Film

@(await Component.InvokeAsync("CategoryFilms", new { categoryName = Model.Category.Name }))

<h1 class="category-name">@Model.Category.Name</h1>

<table id="details-table">
	<tr>
		<td>
			<img class="posters" src="~/obrazki/@Model.Poster" />
		</td>
		<td>
			<p> <b>Tytuł:</b> @Model.Title </p>
			<p> <b>Reżyser:</b> @Model.Director </p>
			<p> <b>Opis:</b> @Model.Desc </p>
			<p> <b>Cena:</b> @Model.Price zł </p>
			<p> <b>Data dodania:</b></> @Model.AddDate?.ToString("dd/MM/yyyy") </p>
		</td>
	</tr>
</table>

<button class="btn btn-outline-primary" onclick="window.location.href='@Url.Action("EditFilm", "Films", new { filmId = Model.FilmId })'"> Edytuj </button>
<button class="btn btn-outline-primary" onclick="window.location.href='@Url.Action("AddToCart", "Cart", new { filmId = Model.FilmId })'"> Dodaj do koszyka </button>

SklepUKW2024/Views/Films/EditFilm.cshtml
@model Film

@(await Component.InvokeAsync("CategoryFilms", new { categoryName = Model.Category.Name }))

<h1 class="category-name">@Model.Category.Name</h1>

@using (Html.BeginForm("EditFilm", "Films", FormMethod.Post))
{
@Html.HiddenFor(f=>f.FilmId)
@Html.HiddenFor(f=>f.Poster)
@Html.HiddenFor(f=>f.CategoryId)
@Html.HiddenFor(f=>f.AddDate)
	
<table id="details-table">
	<tr>
		<td>
			<img class="posters" src="~/obrazki/@Model.Poster" />
		</td>
		<td>
			<p> <b>Tytuł:</b> 
				@Html.EditorFor(f => f.Title, new { @class="form-control"})
			</p>
			<p> <b>Reżyser:</b> 
				@Html.EditorFor(f => f.Director, new { @class="form-control"})
			</p>
			<p> <b>Opis:</b> 
				@Html.EditorFor(f => f.Desc, new { @class="form-control"})
			</p>
			<p> <b>Cena:</b>
				@Html.EditorFor(f => f.Price, new { @class="form-control"})
			</p>
			<p> <b>Data dodania:</b> @Model.AddDate?.ToString("dd/MM/yyyy") </p>
		</td>
	</tr>
</table>
	<button type="submit" class="btn btn-outline-success">Zapisz</button>
}

SklepUKW2024/Views/Films/FilmsList.cshtml
@model IEnumerable<Film>
@{
	//Layout = null;
}

<table class="table table-striped">
	<thead>
		<tr>
			<th>Tytuł filmu</th>
			<th>Reżyser</th>
			<th>Opis</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var film in Model)
		{
			<tr>
				<td>@film.Title</td>
				<td>@film.Director</td>
				<td>@film.Desc</td>
				<td><a href="@Url.Action("Details", "Films", new { filmId = film.FilmId })">🔎</a></td>
				<td><a href="@Url.Action("AddToCart", "Cart", new { filmId = film.FilmId })">🛒</a></td>
			</tr>
		}
	</tbody>
</table>